### ISSUE TITLE
M23 Response

### ISSUE THREAD

**Issue by Wackerbarth** [intelligent-agent/redeem#150]
Our response to `M23` is

```File opened:/usr/share/models/calibration-cube.gcode Lines:16720 Size:443908B```
but, Octoprint is expecting only the file name and size. (Probably because counting lines is too "expensive" on an Arduino board)
```File opened:/usr/share/models/calibration-cube.gcode Size:443908```

Do we want to change our response to match that expectation?

**Comment by goeland86** [comment]
I would suggest that yes, we should match that for the time being.
When OctoPrint 1.4.x comes out and we have a Redeem communication plugin, we'll rework the whole concept to get better feedback about the current print status to OctoPrint. Maybe even manage to let the gcode viewer sync feature work.
